/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 maimai.glb --transform 
Files: maimai.glb [25.11MB] > C:\Users\Tatiana\Desktop\UNI\DP\dp\maimai-transformed.glb [732.26KB] (97%)
Author: EddyNL (https://sketchfab.com/EddyNL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-2077-fanart-makigai-maimai-p126-720ddbe936504ae194d514876b235067
Title: Cyberpunk 2077 fanart: Makigai MaiMai P126
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useConfigurator } from "../../hooks/useConfigurator";

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/maimai-transformed.glb')
  const { actions } = useAnimations(animations, group);

  const { chairColor, lights } = useConfigurator();

  useEffect(() => {
    // materials.Main.color = new Color(chairColor.color);
  }, [materials, chairColor, lights]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Top_door_bone" position={[-0.935, 1.938, 1.131]}>
          <group name="Top_door_bone_1" rotation={[-1.603, 0, 0]}>
            <mesh name="door_heigh" geometry={nodes.door_heigh.geometry} material={materials.TEXTURE} position={[0.935, 1.192, -1.901]} rotation={[1.603, 0, 0]}>
              <group name="Armature" position={[-1.078, 1.401, 0.897]}>
                <group name="Lower_door_bone" position={[0.001, 0.04, 0.367]} rotation={[-1.678, 0, 0.003]}>
                  <mesh name="door_middle" geometry={nodes.door_middle.geometry} material={materials.TEXTURE} position={[1.081, 1.407, -1.297]} rotation={[1.678, -0.003, 0]}>
                    <mesh name="door_heigh001" geometry={nodes.door_heigh001.geometry} material={materials.TEXTURE} position={[-1.172, 1.069, 1.252]} />
                  </mesh>
                </group>
              </group>
            </mesh>
          </group>
        </group>
        <mesh name="12v_battery" geometry={nodes['12v_battery'].geometry} material={materials.TEXTURE} position={[0.901, 1.024, 1.748]} />
        <group name="body_headlight_part001" position={[0, 0.017, -0.001]}>
          <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.headlight} />
          <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials.TEXTURE} />
        </group>
        <mesh name="door_low" geometry={nodes.door_low.geometry} material={materials.TEXTURE} position={[-1.107, 0.368, 0.368]}>
          <mesh name="KONNICHIWA1001" geometry={nodes.KONNICHIWA1001.geometry} material={materials['KONNICHIWA1.001']} position={[-0.076, 0.176, 0.001]} rotation={[-0.825, -0.803, -1.548]} scale={[0.173, 0.173, 0]} />
        </mesh>
        <mesh name="engine_lid" geometry={nodes.engine_lid.geometry} material={materials.TEXTURE} position={[0, 0.872, 1.908]}>
          <mesh name="HYBRID_VTEK004" geometry={nodes.HYBRID_VTEK004.geometry} material={materials['HYBRID VTEK']} position={[-0.829, 0.398, -0.045]} rotation={[0.678, 0, 0]} />
          <mesh name="Makigai_logo" geometry={nodes.Makigai_logo.geometry} material={materials.TEXTURE} position={[0.001, 0.16, -0.036]} rotation={[1.524, 0, 0]} />
          <group name="rear_light_unit" position={[0.784, 0.402, -0.06]} rotation={[0.011, 0, 0]}>
            <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.TEXTURE} />
            <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.headlight} />
          </group>
        </mesh>
        <mesh name="ERROR" geometry={nodes.ERROR.geometry} material={materials.ERROR} position={[-1.129, 1.069, -0.875]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.052} />
        <mesh name="EV_animated_light" geometry={nodes.EV_animated_light.geometry} material={materials['EV lights']} position={[-1.149, 1.042, -0.69]} />
        <mesh name="HYBRID_VTEK003" geometry={nodes.HYBRID_VTEK003.geometry} material={materials['HYBRID VTEK']} position={[0, 1.159, 1.412]} />
        <mesh name="key" geometry={nodes.key.geometry} material={materials.key} position={[-0.546, 1.472, -0.145]} rotation={[1.405, 0, 0]} scale={[0.058, 0.1, 0.1]} />
        <mesh name="license_plate" geometry={nodes.license_plate.geometry} material={materials.Plate} position={[-0.424, 0.445, -1.515]} />
        <mesh name="mesh2" geometry={nodes.mesh2.geometry} material={materials.mesh2} position={[-1.133, 1.326, 1.398]} rotation={[3.062, 0.013, -1.315]} scale={-0.127} />
        <mesh name="nicola_can001" geometry={nodes.nicola_can001.geometry} material={materials.NICOLA} position={[-0.002, 0.746, 0.85]} rotation={[0, 0.686, 0]} />
        <mesh name="Pixel_plate" geometry={nodes.Pixel_plate.geometry} material={materials['Pixel plate']} position={[-0.424, 0.553, -1.533]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.024} />
        <mesh name="roof_unit" geometry={nodes.roof_unit.geometry} material={materials.headlight} position={[0.426, 2.024, 0.349]} rotation={[-0.204, 0, 0]} />
        <mesh name="side_markers" geometry={nodes.side_markers.geometry} material={materials['Side marker']} />
        <mesh name="Wheel006" geometry={nodes.Wheel006.geometry} material={materials.Tyre} position={[0.084, 1.495, 0.625]} rotation={[1.215, -0.065, -0.024]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/maimai-transformed.glb')
